# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env_variables:
  SPRING_DATASOURCE_URL: jdbc:postgresql://${{ secrets.PROD_DB_HOST }}:${{ secrets.PROD_DB_PORT }}/${{ secrets.PROD_DB_NAME }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
  SPRING_PROFILES_ACTIVE: prod
