version: "3.8"

services:
  # Setup database for development
  db:
    image: postgis/postgis:15-3.3
    container_name: mapmates_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mapmates123
      POSTGRES_DB: mapmates_dev
    ports:
      - "5432:5432"
    volumes:
      # Use named volume in dev for persistence
      - postgres_data:/var/lib/postgresql/data
      # Only mount init-scripts in dev
      - ./init-scripts:/docker-entrypoint-initdb.d
    profiles:
      - dev

  # Setup separate database for testing
  db-test:
    image: postgis/postgis:15-3.3
    container_name: mapmates_postgres_test
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mapmates123
      POSTGRES_DB: mapmates_dev
    ports:
      - "5433:5432"
    # Use anonymous volume (wipes after container stops)
    tmpfs:
      - /var/lib/postgresql/data
    profiles:
      - test

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: springboot_server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mapmates_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mapmates123
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
    command: sh -c "./gradlew --stop && ./gradlew bootRun --continuous --no-daemon"
    profiles:
      - dev

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: springboot_test_server
    restart: "no"
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-test:5432/mapmates_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mapmates123
    depends_on:
      - db-test
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
      - ./test-reports:/app/build/reports/tests/test
    command: sh -c "./gradlew --stop && ./gradlew test --no-daemon"

    profiles:
      - test

volumes:
  postgres_data:
