server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: dev

  config:
    activate:
      on-profile: dev
  h2: # Enabling the H2-Console (local and remote)
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://<PROD_DB_HOST>:5432/<DB_NAME>
    driver-class-name: org.postgresql.Driver
    username: <PROD_DB_USERNAME>
    password: <PROD_DB_PASSWORD>
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
