server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://34.59.238.31:5432/mapmates
    username: postgres
    password: mapmates123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev,test
  cloud:
    gcp:
      storage:
        bucket: mapmates-object-store
      secretmanager:
        enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
